export const ENDPOINTURL = {
  MemberLogin: 'ApiLoginValidation/',
  MemberRegister: 'APIAddNewUser/',
  MemberHome: 'ApiGetHomePageData/',
  MemberLock: 'APIOpenCloseBox/',
  MemberUpdateAlarm: 'APIUpdateAlarm/',
  MemberUpdatePIR: 'APIUpdatePIRSensor/',
  MemberUpdateOnDemandCamera: 'APIUpdateOnDemandCamera/',
  MemberMyBox: 'ApiGetMyBoxPageData/',
  MemberAdduser: 'APIAddNewUser/',
  MemberDeleteuser: 'APIDeleteUSER/',
  MemberGetuser: 'ApiGetusers/',
  MemberMobileToken: 'APIUpdateMobileToken/',
  MemberNotification: 'ApiGetNotifications/',
  MemberMobileNotification: 'ApiGetMobileNotifications/',
  MemberUpdateControllerPassword: 'APIUpdateControllerPassword/',
  MemberGetTicketList: 'APIGetTicketList/',
  MemberGetTicketResponse: 'APIGetTicketReponse/',
  MemberSaveTicketResponse: 'APISaveTicketReponse/',
  MemberPackage: 'ApiGetPackageDelivery/',
};
